name: Build and deploy Python app to Azure Web App - 3dmarket

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv env
          source env/bin/activate

      - name: Install dependencies
        run: |
          source env/bin/activate
          pip install -r puddle/requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . -x "env/*" "*.git*" "*.github*" "__pycache__/*" "*.venv*" "*.pytest_cache*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_31B203FD3BA0435B9E7328957E0C0D90 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_13DCC9D2FFAC4B1E83CA304805791D47 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B3A0F1BEEA454B7AB6F895E5AFDEDEA9 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: '3dmarket'
          slot-name: 'Production'

          
